apiVersion: v1
kind: Service
metadata:
  name: muxapp
  labels:
    app: muxapp
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: muxapp
---